### PR TITLE
Introduce new Status/phase: KILLING

### PR DESCRIPTION
**Pull request by juhoautio**
(Building on top of the fixed FlowRunnerTest, PR to origin about that pending here: https://github.com/azkaban/azkaban/pull/1115)

----

Implementation of https://github.com/azkaban/azkaban/issues/1122.

Related to https://github.com/azkaban/azkaban/issues/684.

New status transition after kill is called: -> KILLING -> KILLED.

Don't set the status to KILLED before all job threads have exited.

**TODO**: Also check once more all references to Status.KILLED in Java code.

**TODO** have this merged first \& then rebase on it: https://github.com/azkaban/azkaban/pull/1119

----

nayttokuva 2017-05-26 kello 16 03 05

nayttokuva 2017-05-26 kello 16 02 26

nayttokuva 2017-05-26 kello 16 02 47

### CODE REVIEW

**Comment by HappyRay** [comment]
I can start solo server in Intellij.

**Comment by HappyRay** [comment]
azkaban solo server idea run config

**Comment by juhoautio** [comment]
Would it be possible to share all the required conf files or/and how you created them (like, took some file in git and modified it somehow)?

**Comment by HappyRay** [comment]
Here is my property file
azkaban/temp/conf/azkaban.properties

 # Azkaban Personalization Settings
azkaban.name=Local
azkaban.label=My Local Azkaban
azkaban.color=#FF3601

# this assumes that this file is under a <AZ source root>/<dir>/conf directory
web.resource.dir=../azkaban-web-server/build/install/azkaban-web-server/web
default.timezone.id=America/Los_Angeles

# Azkaban UserManager class
user.manager.class=azkaban.user.XmlUserManager
user.manager.xml.file=conf/azkaban-users.xml

# Loader for projects
executor.global.properties=conf/global.properties
azkaban.project.dir=projects

azkaban.execution.dir=executions

# DB
database.sql.scripts.dir=../azkaban-db/src/main/sql
database.check.version=true
database.auto.update.tables=true

#mysql
database.type=mysql
mysql.port=3306
mysql.host=localhost
mysql.database=azkaban
mysql.numconnections=100

# h2 db
#database.type=h2
#h2.path=data/azkaban
#h2.create.tables=true

azkaban.jobtype.plugin.dir=plugins/jobtypes

# Velocity dev mode
#velocity.dev.mode=false
velocity.dev.mode=true

# Azkaban Jetty server properties. Ignored in tomcat
jetty.use.ssl=false
jetty.ssl.port=8043
jetty.maxThreads=25
jetty.port=8081

# Azkaban Executor settings
executor.maxThreads=50

executor.flow.threads=30

# mail settings
mail.sender=
mail.host=
job.failure.email=
job.success.email=

lockdown.create.projects=false


# JMX stats
jetty.connector.stats=true
executor.connector.stats=true

# uncomment to enable inmemory stats for azkaban
executor.metric.reports=true
executor.metric.milisecinterval.default=60000

**Comment by juhoautio** [comment]
Great!! Seems like that will save me from a lot of trouble. Do you see a way to have this kind of setup available in git so that solo server could run "out of the box" in IDEA?

**Comment by juhoautio** [comment]
Also was discussing this with Liang Tang in gitter.im - I was wondering how less files could be automatically compiled when running the server like that?

**Pull request closed without merging**
